export function generateAIPrompt(metadata) {
  const { meta, datasources, calculated_fields, sheets, parameters, filters } = metadata;
  const lines = [];

  lines.push(`You are analyzing a Tableau workbook. Below is the complete extracted metadata. Use it to answer questions about the workbook's logic, calculated fields, dependencies, and structure.`);
  lines.push(``);
  lines.push(`## WORKBOOK: ${meta.workbook_name}`);
  lines.push(`Tableau ${meta.source_build} | ${meta.source_platform} | ${meta.sheet_count} sheets | ${meta.datasource_count} data sources | ${meta.calculated_field_count} calculated fields | ${meta.parameter_count} parameters`);
  lines.push(``);

  if (calculated_fields.length > 0) {
    lines.push(`## CALCULATED FIELDS (${calculated_fields.length})`);
    for (const cf of calculated_fields) {
      lines.push(`### ${cf.caption} [${cf.datatype}, ${cf.role}] — datasource: ${cf.datasource}`);
      if (cf.dependencies.length > 0) lines.push(`Dependencies: ${cf.dependencies.join(", ")}`);
      lines.push(`Formula: ${cf.formula}`);
      if (cf.description) lines.push(`Description: ${cf.description}`);
      lines.push(``);
    }
  }

  if (datasources.length > 0) {
    lines.push(`## DATA SOURCES (${datasources.length})`);
    for (const ds of datasources) {
      const calcCount = ds.fields.filter(f => f.is_calculated).length;
      lines.push(`### ${ds.caption || ds.name} (${ds.connection_type}) — ${ds.fields.length} fields, ${calcCount} calculated`);
      if (ds.connection_dbname) lines.push(`Database: ${ds.connection_dbname}`);
    }
    lines.push(``);
  }

  if (parameters.length > 0) {
    lines.push(`## PARAMETERS (${parameters.length})`);
    for (const p of parameters) {
      lines.push(`- ${p.caption}: ${p.datatype}, current="${p.current_value}"${p.allowable_values.length > 0 ? `, values=[${p.allowable_values.join(", ")}]` : ""}`);
    }
    lines.push(``);
  }

  if (sheets.length > 0) {
    lines.push(`## SHEETS & DASHBOARDS (${sheets.length})`);
    for (const s of sheets) {
      const parts = [`[${s.type}]`];
      if (s.datasources_used.length > 0) parts.push(`sources: ${s.datasources_used.join(", ")}`);
      if (s.filters_applied.length > 0) parts.push(`filters: ${s.filters_applied.join(", ")}`);
      lines.push(`- ${s.name}: ${parts.join(" | ")}`);
    }
    lines.push(``);
  }

  lines.push(`---`);
  lines.push(`Ask me anything about this workbook: explain a formula, trace a dependency chain, identify unused fields, summarize the data model, or generate dbt model suggestions.`);

  return lines.join("\n");
}

export function generateMarkdown(metadata) {
  const { meta, datasources, calculated_fields, sheets, parameters, filters } = metadata;
  const platform = meta.source_platform === "win" ? "Windows" : meta.source_platform === "mac" ? "macOS" : meta.source_platform;

  const lines = [];

  // Header
  lines.push(`# Workbook Documentation: ${meta.workbook_name}`);
  lines.push(`\n> Generated by TableautoDbt Docs | ${meta.extracted_at}\n`);

  // Overview
  lines.push(`## Overview\n`);
  lines.push(`| Property | Value |`);
  lines.push(`|---|---|`);
  lines.push(`| Source Build | ${meta.source_build} |`);
  lines.push(`| Platform | ${platform} |`);
  lines.push(`| Sheets | ${meta.sheet_count} |`);
  lines.push(`| Data Sources | ${meta.datasource_count} |`);
  lines.push(`| Calculated Fields | ${meta.calculated_field_count} |`);
  lines.push(`| Parameters | ${meta.parameter_count} |`);
  lines.push(`\n---\n`);

  // Data Sources
  if (datasources.length > 0) {
    lines.push(`## Data Sources\n`);
    for (const ds of datasources) {
      lines.push(`### ${ds.caption || ds.name}`);
      lines.push(`- **Connection Type**: ${ds.connection_type}`);
      if (ds.connection_server) lines.push(`- **Server**: ${ds.connection_server}`);
      if (ds.connection_dbname) lines.push(`- **Database**: ${ds.connection_dbname}`);
      lines.push(``);

      if (ds.fields.length > 0) {
        lines.push(`#### Fields (${ds.fields.length} total)\n`);
        lines.push(`| Field | Caption | Type | Role | Calculated |`);
        lines.push(`|---|---|---|---|---|`);
        for (const f of ds.fields) {
          lines.push(`| ${f.name} | ${f.caption} | ${f.datatype} | ${f.role} | ${f.is_calculated ? "Yes" : "No"} |`);
        }
        lines.push(``);
      }
      lines.push(`---\n`);
    }
  }

  // Calculated Fields
  if (calculated_fields.length > 0) {
    lines.push(`## Calculated Fields\n`);
    for (const cf of calculated_fields) {
      lines.push(`### ${cf.caption || cf.name}`);
      lines.push(`- **Datasource**: ${cf.datasource}`);
      lines.push(`- **Datatype**: ${cf.datatype} | **Role**: ${cf.role}`);
      if (cf.dependencies.length > 0) {
        lines.push(`- **Dependencies**: ${cf.dependencies.join(", ")}`);
      }
      if (cf.description) {
        lines.push(`\n${cf.description}\n`);
      }
      lines.push(`\n**Formula**:\n\`\`\``);
      lines.push(cf.formula);
      lines.push(`\`\`\`\n`);
      lines.push(`---\n`);
    }
  }

  // Sheets & Dashboards
  if (sheets.length > 0) {
    lines.push(`## Sheets & Dashboards\n`);
    for (const s of sheets) {
      lines.push(`### ${s.name} (${s.type === "dashboard" ? "Dashboard" : "Worksheet"})`);
      if (s.datasources_used.length > 0) lines.push(`- **Data Sources**: ${s.datasources_used.join(", ")}`);
      if (s.filters_applied.length > 0) lines.push(`- **Filters**: ${s.filters_applied.join(", ")}`);
      if (s.fields_used.length > 0) lines.push(`- **Fields Used**: ${s.fields_used.join(", ")}`);
      lines.push(``);
    }
    lines.push(`---\n`);
  }

  // Parameters
  if (parameters.length > 0) {
    lines.push(`## Parameters\n`);
    for (const p of parameters) {
      lines.push(`### ${p.caption || p.name}`);
      lines.push(`- **Datatype**: ${p.datatype}`);
      lines.push(`- **Current Value**: ${p.current_value}`);
      lines.push(`- **Domain Type**: ${p.domain_type}`);
      if (p.allowable_values.length > 0) {
        lines.push(`- **Allowed Values**: ${p.allowable_values.join(", ")}`);
      }
      if (p.range_min !== null) lines.push(`- **Range**: ${p.range_min} — ${p.range_max}${p.step_size ? ` (step: ${p.step_size})` : ""}`);
      lines.push(``);
    }
    lines.push(`---\n`);
  }

  // Filters
  if (filters.length > 0) {
    lines.push(`## Filters\n`);
    const bySheet = {};
    for (const f of filters) {
      if (!bySheet[f.sheet]) bySheet[f.sheet] = [];
      bySheet[f.sheet].push(f);
    }
    for (const [sheet, sheetFilters] of Object.entries(bySheet)) {
      lines.push(`### ${sheet}\n`);
      for (const f of sheetFilters) {
        lines.push(`#### ${f.field}`);
        lines.push(`- **Type**: ${f.filter_type}`);
        if (f.include_values.length > 0) lines.push(`- **Include**: ${f.include_values.join(", ")}`);
        if (f.exclude_values.length > 0) lines.push(`- **Exclude**: ${f.exclude_values.join(", ")}`);
        if (f.min_value !== null) lines.push(`- **Range**: ${f.min_value} — ${f.max_value}`);
        lines.push(``);
      }
    }
  }

  return lines.join("\n");
}
