export function generateAIPrompt(metadata) {
  const { meta, datasources, calculated_fields, sheets, parameters, filters } = metadata;
  const lines = [];

  lines.push(`You are analyzing a Tableau workbook. Below is the complete extracted metadata. Use it to answer questions about the workbook's logic, calculated fields, dependencies, and structure.`);
  lines.push(``);
  lines.push(`## WORKBOOK: ${meta.workbook_name}`);
  lines.push(`Tableau ${meta.source_build} | ${meta.source_platform} | ${meta.sheet_count} sheets | ${meta.datasource_count} data sources | ${meta.calculated_field_count} calculated fields | ${meta.parameter_count} parameters`);
  lines.push(``);

  if (calculated_fields.length > 0) {
    lines.push(`## CALCULATED FIELDS (${calculated_fields.length})`);
    for (const cf of calculated_fields) {
      lines.push(`### ${cf.caption} [${cf.datatype}, ${cf.role}] — datasource: ${cf.datasource}`);
      if (cf.dependencies.length > 0) lines.push(`Dependencies: ${cf.dependencies.join(", ")}`);
      lines.push(`Formula: ${cf.formula}`);
      if (cf.description) lines.push(`Description: ${cf.description}`);
      lines.push(``);
    }
  }

  if (datasources.length > 0) {
    lines.push(`## DATA SOURCES (${datasources.length})`);
    for (const ds of datasources) {
      const calcCount = ds.fields.filter(f => f.is_calculated).length;
      lines.push(`### ${ds.caption || ds.name} (${ds.connection_type}) — ${ds.fields.length} fields, ${calcCount} calculated`);
      if (ds.connection_dbname) lines.push(`Database: ${ds.connection_dbname}`);
    }
    lines.push(``);
  }

  if (parameters.length > 0) {
    lines.push(`## PARAMETERS (${parameters.length})`);
    for (const p of parameters) {
      lines.push(`- ${p.caption}: ${p.datatype}, current="${p.current_value}"${p.allowable_values.length > 0 ? `, values=[${p.allowable_values.join(", ")}]` : ""}`);
    }
    lines.push(``);
  }

  if (sheets.length > 0) {
    lines.push(`## SHEETS & DASHBOARDS (${sheets.length})`);
    for (const s of sheets) {
      const parts = [`[${s.type}]`];
      if (s.datasources_used.length > 0) parts.push(`sources: ${s.datasources_used.join(", ")}`);
      if (s.filters_applied.length > 0) parts.push(`filters: ${s.filters_applied.join(", ")}`);
      lines.push(`- ${s.name}: ${parts.join(" | ")}`);
    }
    lines.push(``);
  }

  lines.push(`---`);
  lines.push(`Ask me anything about this workbook: explain a formula, trace a dependency chain, identify unused fields, summarize the data model, or generate dbt model suggestions.`);

  return lines.join("\n");
}

export function generateMarkdown(metadata) {
  const { meta, datasources, calculated_fields, sheets, parameters, filters } = metadata;
  const platform = meta.source_platform === "win" ? "Windows" : meta.source_platform === "mac" ? "macOS" : meta.source_platform;

  const lines = [];

  // Header
  lines.push(`# Workbook Documentation: ${meta.workbook_name}`);
  lines.push(`\n> Generated by TableautoDbt Docs | ${meta.extracted_at}\n`);

  // Overview
  lines.push(`## Overview\n`);
  lines.push(`| Property | Value |`);
  lines.push(`|---|---|`);
  lines.push(`| Source Build | ${meta.source_build} |`);
  lines.push(`| Platform | ${platform} |`);
  lines.push(`| Sheets | ${meta.sheet_count} |`);
  lines.push(`| Data Sources | ${meta.datasource_count} |`);
  lines.push(`| Calculated Fields | ${meta.calculated_field_count} |`);
  lines.push(`| Parameters | ${meta.parameter_count} |`);
  lines.push(`\n---\n`);

  // Data Sources
  if (datasources.length > 0) {
    lines.push(`## Data Sources\n`);
    for (const ds of datasources) {
      lines.push(`### ${ds.caption || ds.name}`);
      lines.push(`- **Connection Type**: ${ds.connection_type}`);
      if (ds.connection_server) lines.push(`- **Server**: ${ds.connection_server}`);
      if (ds.connection_dbname) lines.push(`- **Database**: ${ds.connection_dbname}`);
      lines.push(``);

      if (ds.fields.length > 0) {
        lines.push(`#### Fields (${ds.fields.length} total)\n`);
        lines.push(`| Field | Caption | Type | Role | Calculated |`);
        lines.push(`|---|---|---|---|---|`);
        for (const f of ds.fields) {
          lines.push(`| ${f.name} | ${f.caption} | ${f.datatype} | ${f.role} | ${f.is_calculated ? "Yes" : "No"} |`);
        }
        lines.push(``);
      }
      lines.push(`---\n`);
    }
  }

  // Calculated Fields
  if (calculated_fields.length > 0) {
    lines.push(`## Calculated Fields\n`);
    for (const cf of calculated_fields) {
      lines.push(`### ${cf.caption || cf.name}`);
      lines.push(`- **Datasource**: ${cf.datasource}`);
      lines.push(`- **Datatype**: ${cf.datatype} | **Role**: ${cf.role}`);
      if (cf.dependencies.length > 0) {
        lines.push(`- **Dependencies**: ${cf.dependencies.join(", ")}`);
      }
      if (cf.description) {
        lines.push(`\n${cf.description}\n`);
      }
      lines.push(`\n**Formula**:\n\`\`\``);
      lines.push(cf.formula);
      lines.push(`\`\`\`\n`);
      lines.push(`---\n`);
    }
  }

  // Sheets & Dashboards
  if (sheets.length > 0) {
    lines.push(`## Sheets & Dashboards\n`);
    for (const s of sheets) {
      lines.push(`### ${s.name} (${s.type === "dashboard" ? "Dashboard" : "Worksheet"})`);
      if (s.datasources_used.length > 0) lines.push(`- **Data Sources**: ${s.datasources_used.join(", ")}`);
      if (s.filters_applied.length > 0) lines.push(`- **Filters**: ${s.filters_applied.join(", ")}`);
      if (s.fields_used.length > 0) lines.push(`- **Fields Used**: ${s.fields_used.join(", ")}`);
      lines.push(``);
    }
    lines.push(`---\n`);
  }

  // Parameters
  if (parameters.length > 0) {
    lines.push(`## Parameters\n`);
    for (const p of parameters) {
      lines.push(`### ${p.caption || p.name}`);
      lines.push(`- **Datatype**: ${p.datatype}`);
      lines.push(`- **Current Value**: ${p.current_value}`);
      lines.push(`- **Domain Type**: ${p.domain_type}`);
      if (p.allowable_values.length > 0) {
        lines.push(`- **Allowed Values**: ${p.allowable_values.join(", ")}`);
      }
      if (p.range_min !== null) lines.push(`- **Range**: ${p.range_min} — ${p.range_max}${p.step_size ? ` (step: ${p.step_size})` : ""}`);
      lines.push(``);
    }
    lines.push(`---\n`);
  }

  // Filters
  if (filters.length > 0) {
    lines.push(`## Filters\n`);
    const bySheet = {};
    for (const f of filters) {
      if (!bySheet[f.sheet]) bySheet[f.sheet] = [];
      bySheet[f.sheet].push(f);
    }
    for (const [sheet, sheetFilters] of Object.entries(bySheet)) {
      lines.push(`### ${sheet}\n`);
      for (const f of sheetFilters) {
        lines.push(`#### ${f.field}`);
        lines.push(`- **Type**: ${f.filter_type}`);
        if (f.include_values.length > 0) lines.push(`- **Include**: ${f.include_values.join(", ")}`);
        if (f.exclude_values.length > 0) lines.push(`- **Exclude**: ${f.exclude_values.join(", ")}`);
        if (f.min_value !== null) lines.push(`- **Range**: ${f.min_value} — ${f.max_value}`);
        lines.push(``);
      }
    }
  }

  return lines.join("\n");
}

export function generateNotionMarkdown(metadata) {
  const { meta, datasources, calculated_fields, sheets, parameters, filters } = metadata;
  const platform = meta.source_platform === "win" ? "Windows" : meta.source_platform === "mac" ? "macOS" : meta.source_platform;
  const lines = [];

  lines.push(`# 📊 ${meta.workbook_name}`);
  lines.push(`\n> 🤖 Generated by **TableautoDbt Docs** | ${meta.extracted_at}\n`);
  lines.push(`> **${meta.calculated_field_count}** calculated fields · **${meta.datasource_count}** data sources · **${meta.sheet_count}** sheets · **${meta.parameter_count}** parameters · Tableau ${meta.source_build} (${platform})\n`);

  if (calculated_fields.length > 0) {
    lines.push(`---\n`);
    lines.push(`## 🧮 Calculated Fields\n`);
    for (const cf of calculated_fields) {
      lines.push(`### ${cf.caption}`);
      lines.push(`**Datasource:** ${cf.datasource} · **Type:** ${cf.datatype} · **Role:** ${cf.role}`);
      if (cf.dependencies.length > 0) lines.push(`**Depends on:** ${cf.dependencies.map(d => `\`${d}\``).join(", ")}`);
      if (cf.description) lines.push(`\n${cf.description}`);
      lines.push(`\n\`\`\`\n${cf.formula}\n\`\`\`\n`);
    }
  }

  if (datasources.length > 0) {
    lines.push(`---\n`);
    lines.push(`## 🗄 Data Sources\n`);
    for (const ds of datasources) {
      const calcCount = ds.fields.filter(f => f.is_calculated).length;
      lines.push(`### ${ds.caption || ds.name}`);
      lines.push(`**Connection:** ${ds.connection_type}${ds.connection_dbname ? ` · **Database:** ${ds.connection_dbname}` : ""} · ${ds.fields.length} fields (${calcCount} calculated)\n`);
    }
  }

  if (sheets.length > 0) {
    lines.push(`---\n`);
    lines.push(`## 📊 Sheets & Dashboards\n`);
    lines.push(`| Name | Type | Sources | Fields |`);
    lines.push(`|---|---|---|---|`);
    for (const s of sheets) {
      const fields = s.fields_used.slice(0, 5).map(f => f.replace(/^\[|\]$/g, "")).join(", ") + (s.fields_used.length > 5 ? ` +${s.fields_used.length - 5} more` : "");
      lines.push(`| **${s.name}** | ${s.type === "dashboard" ? "Dashboard" : "Worksheet"} | ${s.datasources_used.join(", ") || "—"} | ${fields || "—"} |`);
    }
    lines.push(``);
  }

  if (parameters.length > 0) {
    lines.push(`---\n`);
    lines.push(`## 🎛 Parameters\n`);
    lines.push(`| Name | Type | Current Value | Domain |`);
    lines.push(`|---|---|---|---|`);
    for (const p of parameters) lines.push(`| **${p.caption || p.name}** | ${p.datatype} | \`${p.current_value}\` | ${p.domain_type} |`);
    lines.push(``);
  }

  if (filters.length > 0) {
    lines.push(`---\n`);
    lines.push(`## 🔍 Filters\n`);
    const bySheet = {};
    for (const f of filters) { if (!bySheet[f.sheet]) bySheet[f.sheet] = []; bySheet[f.sheet].push(f); }
    for (const [sheet, sf] of Object.entries(bySheet)) {
      lines.push(`### ${sheet}\n`);
      for (const f of sf) {
        const vals = f.include_values.length > 0 ? `Include: ${f.include_values.slice(0, 5).join(", ")}` : f.exclude_values.length > 0 ? `Exclude: ${f.exclude_values.slice(0, 5).join(", ")}` : f.min_value !== null ? `Range: ${f.min_value}–${f.max_value}` : "";
        lines.push(`- **${f.field.replace(/^\[|\]$/g, "")}** (${f.filter_type})${vals ? `: ${vals}` : ""}`);
      }
      lines.push(``);
    }
  }

  return lines.join("\n");
}

export function generateConfluenceMarkup(metadata) {
  const { meta, datasources, calculated_fields, sheets, parameters, filters } = metadata;
  const platform = meta.source_platform === "win" ? "Windows" : meta.source_platform === "mac" ? "macOS" : meta.source_platform;
  const lines = [];

  lines.push(`h1. ${meta.workbook_name}`);
  lines.push(``);
  lines.push(`{info:title=Workbook Overview}`);
  lines.push(`Generated by TableautoDbt Docs | ${meta.extracted_at}`);
  lines.push(`Tableau ${meta.source_build} | ${platform} | ${meta.calculated_field_count} calculated fields | ${meta.datasource_count} data sources | ${meta.sheet_count} sheets | ${meta.parameter_count} parameters`);
  lines.push(`{info}`);
  lines.push(``);

  if (calculated_fields.length > 0) {
    lines.push(`h2. Calculated Fields (${calculated_fields.length})`);
    lines.push(``);
    for (const cf of calculated_fields) {
      lines.push(`h3. ${cf.caption}`);
      lines.push(`*Datasource:* ${cf.datasource} | *Type:* ${cf.datatype} | *Role:* ${cf.role}`);
      if (cf.dependencies.length > 0) lines.push(`*Depends on:* ${cf.dependencies.join(", ")}`);
      if (cf.description) lines.push(cf.description);
      lines.push(``);
      lines.push(`{code:title=Formula|borderStyle=solid}`);
      lines.push(cf.formula);
      lines.push(`{code}`);
      lines.push(``);
      lines.push(`----`);
      lines.push(``);
    }
  }

  if (datasources.length > 0) {
    lines.push(`h2. Data Sources (${datasources.length})`);
    lines.push(``);
    for (const ds of datasources) {
      lines.push(`h3. ${ds.caption || ds.name}`);
      lines.push(`*Connection:* ${ds.connection_type}${ds.connection_dbname ? ` | *Database:* ${ds.connection_dbname}` : ""}`);
      lines.push(``);
      if (ds.fields.length > 0) {
        lines.push(`||Field||Caption||Type||Role||Calculated||`);
        for (const f of ds.fields) lines.push(`|${f.name}|${f.caption}|${f.datatype}|${f.role}|${f.is_calculated ? "Yes" : "No"}|`);
      }
      lines.push(``);
    }
  }

  if (sheets.length > 0) {
    lines.push(`h2. Sheets & Dashboards (${sheets.length})`);
    lines.push(``);
    lines.push(`||Name||Type||Data Sources||Fields||`);
    for (const s of sheets) {
      const fields = s.fields_used.slice(0, 5).map(f => f.replace(/^\[|\]$/g, "")).join(", ") + (s.fields_used.length > 5 ? ` +${s.fields_used.length - 5} more` : "");
      lines.push(`|${s.name}|${s.type === "dashboard" ? "Dashboard" : "Worksheet"}|${s.datasources_used.join(", ") || "—"}|${fields || "—"}|`);
    }
    lines.push(``);
  }

  if (parameters.length > 0) {
    lines.push(`h2. Parameters (${parameters.length})`);
    lines.push(``);
    lines.push(`||Name||Type||Current Value||Domain||`);
    for (const p of parameters) lines.push(`|${p.caption || p.name}|${p.datatype}|${p.current_value}|${p.domain_type}|`);
    lines.push(``);
  }

  if (filters.length > 0) {
    lines.push(`h2. Filters (${filters.length})`);
    lines.push(``);
    const bySheet = {};
    for (const f of filters) { if (!bySheet[f.sheet]) bySheet[f.sheet] = []; bySheet[f.sheet].push(f); }
    for (const [sheet, sf] of Object.entries(bySheet)) {
      lines.push(`h3. ${sheet}`);
      lines.push(`||Field||Type||Values||`);
      for (const f of sf) {
        const vals = f.include_values.length > 0 ? `Include: ${f.include_values.slice(0, 5).join(", ")}` : f.exclude_values.length > 0 ? `Exclude: ${f.exclude_values.slice(0, 5).join(", ")}` : f.min_value !== null ? `Range: ${f.min_value}–${f.max_value}` : "—";
        lines.push(`|${f.field.replace(/^\[|\]$/g, "")}|${f.filter_type}|${vals}|`);
      }
      lines.push(``);
    }
  }

  return lines.join("\n");
}

export function generateAuditMarkdown(result) {
  const { meta, summary, fields } = result;
  const lines = [];

  lines.push(`# Audit Report: ${meta.workbook_name}`);
  lines.push(`\n> Generated by TableautoDbt Audit | ${meta.audited_at}\n`);

  lines.push(`## Health Score: ${meta.health_score}/100\n`);
  lines.push(`| Metric | Count |`);
  lines.push(`|---|---|`);
  lines.push(`| Total Calculated Fields | ${meta.total_calculated_fields} |`);
  lines.push(`| Errors | ${meta.issue_breakdown.error} |`);
  lines.push(`| Warnings | ${meta.issue_breakdown.warning} |`);
  lines.push(`| Info | ${meta.issue_breakdown.info} |`);
  lines.push(`\n---\n`);

  lines.push(`## Summary\n`);
  if (summary.unused_fields.length > 0) lines.push(`- **Unused Fields (${summary.unused_fields.length})**: ${summary.unused_fields.join(", ")}`);
  if (summary.high_complexity_fields.length > 0) lines.push(`- **High Complexity (${summary.high_complexity_fields.length})**: ${summary.high_complexity_fields.join(", ")}`);
  if (summary.performance_issues.length > 0) lines.push(`- **Performance Issues (${summary.performance_issues.length})**: ${summary.performance_issues.join(", ")}`);
  if (summary.circular_dependencies.length > 0) lines.push(`- **Circular Dependencies**: ${summary.circular_dependencies.join(", ")}`);
  lines.push(`\n---\n`);

  const fieldsWithIssues = fields.filter(f => f.issues.length > 0);
  if (fieldsWithIssues.length > 0) {
    lines.push(`## Fields Needing Attention (${fieldsWithIssues.length})\n`);
    for (const f of fieldsWithIssues) {
      lines.push(`### ${f.caption}`);
      lines.push(`- **Datasource**: ${f.datasource}`);
      lines.push(`- **Complexity**: ${f.complexity_label} (score: ${f.complexity_score}, nesting: ${f.nesting_depth})`);
      if (f.unused) lines.push(`- **Unused**: Yes`);
      if (f.dependencies.length > 0) lines.push(`- **Dependencies**: ${f.dependencies.join(", ")}`);
      lines.push(`\n**Issues**:`);
      for (const issue of f.issues) lines.push(`- [${issue.severity.toUpperCase()}] ${issue.message}`);
      lines.push(`\n**Formula**:\n\`\`\``);
      lines.push(f.formula);
      lines.push(`\`\`\`\n`);
      lines.push(`---\n`);
    }
  }

  lines.push(`## All Calculated Fields (${fields.length})\n`);
  lines.push(`| Field | Datasource | Complexity | Nesting | Issues | Unused |`);
  lines.push(`|---|---|---|---|---|---|`);
  for (const f of fields) {
    lines.push(`| ${f.caption} | ${f.datasource} | ${f.complexity_label} | ${f.nesting_depth} | ${f.issues.length} | ${f.unused ? "Yes" : "No"} |`);
  }

  return lines.join("\n");
}

export function generateAuditAIPrompt(result) {
  const { meta, summary, fields } = result;
  const lines = [];

  lines.push(`You are reviewing a Tableau workbook audit report. Below is the complete audit data. Use it to answer questions, explain issues, suggest fixes, or prioritize remediation.`);
  lines.push(``);
  lines.push(`## WORKBOOK: ${meta.workbook_name}`);
  lines.push(`Health Score: ${meta.health_score}/100 | ${meta.total_calculated_fields} calculated fields | Errors: ${meta.issue_breakdown.error} | Warnings: ${meta.issue_breakdown.warning} | Info: ${meta.issue_breakdown.info}`);
  lines.push(``);
  lines.push(`## SUMMARY`);
  if (summary.unused_fields.length > 0) lines.push(`Unused fields (${summary.unused_fields.length}): ${summary.unused_fields.join(", ")}`);
  if (summary.high_complexity_fields.length > 0) lines.push(`High complexity (${summary.high_complexity_fields.length}): ${summary.high_complexity_fields.join(", ")}`);
  if (summary.performance_issues.length > 0) lines.push(`Performance issues (${summary.performance_issues.length}): ${summary.performance_issues.join(", ")}`);
  if (summary.circular_dependencies.length > 0) lines.push(`Circular dependencies: ${summary.circular_dependencies.join(", ")}`);
  lines.push(``);

  const fieldsWithIssues = fields.filter(f => f.issues.length > 0);
  lines.push(`## FIELDS WITH ISSUES (${fieldsWithIssues.length})`);
  for (const f of fieldsWithIssues) {
    lines.push(`### ${f.caption} [${f.complexity_label}, depth:${f.nesting_depth}${f.unused ? ", UNUSED" : ""}] — datasource: ${f.datasource}`);
    if (f.dependencies.length > 0) lines.push(`Dependencies: ${f.dependencies.join(", ")}`);
    for (const issue of f.issues) lines.push(`[${issue.severity.toUpperCase()}] ${issue.message} (${issue.rule})`);
    lines.push(`Formula: ${f.formula}`);
    lines.push(``);
  }

  lines.push(`---`);
  lines.push(`Ask me anything: explain an issue, suggest a fix, prioritize what to address first, or generate refactored Tableau formulas.`);

  return lines.join("\n");
}

export function generateAuditNotionMarkdown(result) {
  const { meta, summary, fields } = result;
  const lines = [];

  lines.push(`# 🔍 Audit: ${meta.workbook_name}`);
  lines.push(`\n> 🤖 Generated by **TableautoDbt Audit** | ${meta.audited_at}\n`);
  lines.push(`> **Health Score: ${meta.health_score}/100** · ${meta.total_calculated_fields} fields · ${meta.issue_breakdown.error} errors · ${meta.issue_breakdown.warning} warnings\n`);
  lines.push(`---\n`);
  lines.push(`## 📋 Summary\n`);
  if (summary.unused_fields.length > 0) lines.push(`**Unused Fields (${summary.unused_fields.length}):** ${summary.unused_fields.map(f => `\`${f}\``).join(", ")}\n`);
  if (summary.high_complexity_fields.length > 0) lines.push(`**High Complexity (${summary.high_complexity_fields.length}):** ${summary.high_complexity_fields.map(f => `\`${f}\``).join(", ")}\n`);
  if (summary.performance_issues.length > 0) lines.push(`**Performance Issues (${summary.performance_issues.length}):** ${summary.performance_issues.map(f => `\`${f}\``).join(", ")}\n`);
  if (summary.circular_dependencies.length > 0) lines.push(`**Circular Dependencies:** ${summary.circular_dependencies.map(f => `\`${f}\``).join(", ")}\n`);

  const fieldsWithIssues = fields.filter(f => f.issues.length > 0);
  if (fieldsWithIssues.length > 0) {
    lines.push(`---\n`);
    lines.push(`## ⚠️ Fields Needing Attention\n`);
    for (const f of fieldsWithIssues) {
      lines.push(`### ${f.caption}`);
      lines.push(`**Datasource:** ${f.datasource} · **Complexity:** ${f.complexity_label} · **Nesting:** ${f.nesting_depth}${f.unused ? " · **UNUSED**" : ""}`);
      for (const issue of f.issues) {
        const emoji = issue.severity === "error" ? "🔴" : issue.severity === "warning" ? "🟡" : "🔵";
        lines.push(`- ${emoji} ${issue.message}`);
      }
      lines.push(`\n\`\`\`\n${f.formula}\n\`\`\`\n`);
    }
  }

  lines.push(`---\n`);
  lines.push(`## 📊 All Fields\n`);
  lines.push(`| Field | Datasource | Complexity | Issues | Unused |`);
  lines.push(`|---|---|---|---|---|`);
  for (const f of fields) {
    const badge = f.issues.length > 0 ? `⚠️ ${f.issues.length}` : "✅ 0";
    lines.push(`| **${f.caption}** | ${f.datasource} | ${f.complexity_label} | ${badge} | ${f.unused ? "Yes" : "—"} |`);
  }

  return lines.join("\n");
}

export function generateAuditConfluenceMarkup(result) {
  const { meta, summary, fields } = result;
  const lines = [];

  lines.push(`h1. Audit Report: ${meta.workbook_name}`);
  lines.push(``);
  lines.push(`{info:title=Audit Overview}`);
  lines.push(`Generated by TableautoDbt Audit | ${meta.audited_at}`);
  lines.push(`Health Score: ${meta.health_score}/100 | ${meta.total_calculated_fields} calculated fields | Errors: ${meta.issue_breakdown.error} | Warnings: ${meta.issue_breakdown.warning} | Info: ${meta.issue_breakdown.info}`);
  lines.push(`{info}`);
  lines.push(``);

  lines.push(`h2. Summary`);
  lines.push(``);
  if (summary.unused_fields.length > 0) lines.push(`*Unused Fields (${summary.unused_fields.length}):* ${summary.unused_fields.join(", ")}`);
  if (summary.high_complexity_fields.length > 0) lines.push(`*High Complexity (${summary.high_complexity_fields.length}):* ${summary.high_complexity_fields.join(", ")}`);
  if (summary.performance_issues.length > 0) lines.push(`*Performance Issues (${summary.performance_issues.length}):* ${summary.performance_issues.join(", ")}`);
  if (summary.circular_dependencies.length > 0) lines.push(`*Circular Dependencies:* ${summary.circular_dependencies.join(", ")}`);
  lines.push(``);

  const fieldsWithIssues = fields.filter(f => f.issues.length > 0);
  if (fieldsWithIssues.length > 0) {
    lines.push(`h2. Fields Needing Attention (${fieldsWithIssues.length})`);
    lines.push(``);
    for (const f of fieldsWithIssues) {
      lines.push(`h3. ${f.caption}`);
      lines.push(`*Datasource:* ${f.datasource} | *Complexity:* ${f.complexity_label} | *Nesting:* ${f.nesting_depth}${f.unused ? " | *UNUSED*" : ""}`);
      if (f.dependencies.length > 0) lines.push(`*Dependencies:* ${f.dependencies.join(", ")}`);
      lines.push(``);
      lines.push(`||Severity||Issue||Rule||`);
      for (const issue of f.issues) lines.push(`|${issue.severity}|${issue.message}|${issue.rule}|`);
      lines.push(``);
      lines.push(`{code:title=Formula|borderStyle=solid}`);
      lines.push(f.formula);
      lines.push(`{code}`);
      lines.push(``);
      lines.push(`----`);
      lines.push(``);
    }
  }

  lines.push(`h2. All Calculated Fields (${fields.length})`);
  lines.push(``);
  lines.push(`||Field||Datasource||Complexity||Nesting||Issues||Unused||`);
  for (const f of fields) lines.push(`|${f.caption}|${f.datasource}|${f.complexity_label}|${f.nesting_depth}|${f.issues.length}|${f.unused ? "Yes" : "No"}|`);

  return lines.join("\n");
}
